name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-run-docker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Run Docker container (Local Testing)
        run: |
          docker run -d -p 3000:3000 --name my-app-container my-app:latest
          sleep 10  # Give it time to start
          curl -f http://localhost:3000 || (echo "Container failed to start" && exit 1)

      - name: Stop and remove container
        if: always()
        run: docker stop my-app-container && docker rm my-app-container

