name: CI/CD Pipeline

on:
  push:
    branches:
      - week-2
  pull_request:
    branches:
      - week-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Run Container
        run: |
          docker run --rm my-app:latest

