version: '3.8'
services:
  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
  fastapi-app:
    build: ./fastapi-app
    ports:
      - "8000:8000"
  nextjs-app:
    build: ./nextjs-app
    ports:
      - "3000:3000"
