name: CI/CD Pipeline for Week 2

on:  
  push:
    branches:
      - week-2  # Trigger when pushing to week-2 branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version

      - name: Build Docker Image
        run: docker build -t my-app .

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 my-app

